### PR TITLE
Add note about may need to use sude

### PR DESCRIPTION
**Pull request by aturkewi**
Fixes issue #2 

There are not changes to that second chunk of text (and I'm not sure why that's showing up). I tried to start from the current master and just re-add my note. When I checked the chages with `git diff` it showed that section changed again. 

@ipc103 @PeterBell

### CODE REVIEW

**Comment by ipc103** [comment]
don't think students should need to use sudo to install that - @pletcher can you confirm this?

**Comment by aturkewi** [comment]
For reference. I was able to re-create the need for sudo when in first uninstalled and then re-installed protractor.

**Comment by ipc103** [comment]
I think the issue is that protractor is being install with sudo, therefore webdriver-manager must be installed/updated with sudo. I think we should change this to just be `npm install -g protractor` - @PeterBell what do you think?

**Comment by pletcher** [comment]
Yeah, we almost certainly don't want `sudo` here -- needing it points to some permissions troubles that will plague students until they fix them.

We should make sure that they've installed `node` and `npm` in a sane way so that their global packages have the correct permissions. (For development, 775 should be perfectly safe.) If they're using `brew`, this should be taken care of for them; but they might need to do some `chmod`ing if not.

**Pull request closed without merging**
